### DISCUSSION TITLE
Exit Delay In Progress Status

### DISCUSSION THREAD

**Discussion by BobRobertBob** [ufodone/envisalink_new#133] [Q&A] [answered]
I am attempting to use the condition "Exit delay" is true in an Automation and can't seem to get it to work, at least not directly.

This does not work:
condition:
  - condition: state
    entity_id: sensor.home_alarm_keypad
    attribute: exit_delay
    enabled: true
    state: 'true'

However the following does work:
condition:
  - condition: state
    entity_id: sensor.home_alarm_keypad
    attribute: alpha
    enabled: true
    state: Exit Delay In Progress

I can use the 2nd method to achieve what I'm trying to do, I'm just trying to understand why looking at the attribute "exit delay" being true doesn't work.

**Comment by ufodone** [comment]
The yaml snippets you provided are the condition for your automation.  What trigger are you using?

A trigger like this:
```
trigger:
  - platform: state
    entity_id:
      - sensor.home_alarm_keypad
    attribute: exit_delay
    to: true
```

works when I try it.  Note that the `to` field must not have the `true` quoted.

In your example, you might try changing `state: 'true'` to `state: true`.
