### ISSUE TITLE
Unrecognized/Uncofigured panel type error

### ISSUE THREAD

**Issue by jacobcurulli** [ufodone/envisalink_new#100]
Hi,

I have an Envisalink3 board and this integration has been working great. But I occasionally get an error message:
Unrecognized/Unconfigured panel type error at "board ip":4025

Rebooting the board seems to resolve the issue.

Kind regards,

**Comment by ufodone** [comment]
What firmware version is your EVL3 running?  Some of the older firmware could become unresponsive which could result in this type of error.

If you are running the latest firmware, could you enable debug logging and post the log with this happening?  Debug logging can be turned on by adding something like this to your configuration.yaml:

```
logger:
  default: info
  logs:
    custom_components.envisalink_new: debug
```
