### ISSUE TITLE
PGM Setup

### ISSUE THREAD

**Issue by durosity** [ufodone/envisalink_new#110]
I use the PGM outputs on my DSC alarm for a few different things (pgm1 garage door, pgm2 reset smoke detector, pga3 garden sprinklers, pgm4 shed door lock).  I found a prior issue raised about it and it suggests adding to the configuration.yaml:

```
service: envisalink_new.invoke_custom_function
data:
  pgm: 2
target:
  entity_id: alarm_control_panel.home_alarm

```
However when I add this I just get errors in the logs:

 ```
Setup failed for 'service': Integration not found. 
 17:32:43 – (ERROR) setup.py - message first occurred at 17:32:43 and shows up 3 times
```

And I'm not entirely sure what needs to be done to resolve this.  

I'm pretty new to hats so please excuse my lack of experience with this system if it's something blatantly obvious!
