### ISSUE TITLE
Pre-release v1.0.0-beta1 - Mushroom Entity Card Activity

### ISSUE THREAD

**Issue by garyak** [ufodone/envisalink_new#165]
Following installation of v1.0.0-beta1 and removal of the alarm code from EyesOn Basic configuration, my chime entity appeared as unknown in the mushroom entity card. 

![chime](https://github.com/user-attachments/assets/b8a42505-db92-4baf-8180-f81354ecaedb)

Here's the chime script:

```
door_chime:
  alias: Door Chime
  icon: mdi:music-note
  mode: single
  sequence:
  - data:
      keypress: 06249
    entity_id: alarm_control_panel.alarm
    service: envisalink_new.alarm_keypress
```
Note the toggle action of the continues to work as expected, but the icon does not change to indicate the state as shown here when the alarm code is included in EyesOn Basic configuration.

![chime1](https://github.com/user-attachments/assets/6361b9f6-44ee-4c1f-8882-916e83c331a3)

If I specify an alarm code in the EyesOn Basic configuration the mushroom card handles the entity correctly.

**Comment by ufodone** [comment]
If I understand correctly, you have a mushroom entity card that you use to toggle the chime on the panel?  And the toggle action itself still works but the state isn't showing up correctly?  If so, where is the card configured to get its state from?

The integration creates a chime switch entity automatically and looking at the code, I can see how that is likely broken with this release so I'll fix that.  But it doesn't sound like you are using that entity and are instead simulating it with your script?

**Comment by garyak** [comment]
Yes. I may have confused the card by improper configuration.

```
     - type: custom:mushroom-entity-card
        entity: switch.alarm_panel_chime
        name: Chime
        icon: mdi:alarm-note
        layout: vertical
        tap_action:
          action: perform-action
          perform_action: script.door_chime
          target: {}
        hold_action:
          action: more-info
        double_tap_action:
          action: none
        primary_info: name
        secondary_info: none
        fill_container: false
```
It seems I've blended both in the card config. I'm not sure where the card gets its entity status.

**Comment by ufodone** [comment]
I see the issue now.  The chime switch entity doesn't get created if `code` isn't set and I forgot to update it to use the default code stored on the alarm_control_panel_entity.  I'll get a fix out shortly.

Unrelated, but I suspect you can eliminate your `door_chime` script on that card now and just use the switch entity itself.  Maybe that was something you had before the integration created the entity?

**Comment by garyak** [comment]
I'll modify the card code to rely solely on the switch entity. I did use the script with the native Envisalink integration. I'll update to your latest when released and let you know the results.

**Comment by ufodone** [comment]
I've published a new [v1.0.0-beta2](https://github.com/ufodone/envisalink_new/releases/tag/v1.0.0-beta2) release which should fix this issue.

Thanks for giving the beta a try and providing feedback!  The changes were fairly extensive so I'd hoped some folks would try it out before I made a full release.

**Comment by garyak** [comment]
`switch.alarm_panel_chime` state is unknown with b2 release when alarm code is missing from EyesOn configuration. If I add the code, I get state information and the card functions as expected.

Here's the revised card:
```
      - type: custom:mushroom-entity-card
        entity: switch.alarm_panel_chime
        name: Chime
        icon: mdi:alarm-note
        layout: vertical
        tap_action:
          action: perform-action
          perform_action: switch.toggle
          target:
            entity_id: switch.alarm_panel_chime
        hold_action:
          action: more-info
        double_tap_action:
          action: none
        primary_info: name
        secondary_info: none
        fill_container: false
```
