### ISSUE TITLE
Home Assistant and Node Red

### ISSUE THREAD

**Issue by vitodcampanelli** [ufodone/envisalink_new#192]
Hello,

Does anybody have a node-red flow that is used to arm or disarm the UNO Panel?
I am struggling to find the correct services to call using the envisalink_new?
If this is not possible, will there be an integration in the future?

Thanks

**Comment by ufodone** [comment]
I've never used node-red but to arm/disarm the panel via an action you need to use the `alarm_control_panel` actions.  For example, to arm the panel in away mode, the YAML for the action would look something like:

```
action: alarm_control_panel.alarm_arm_away
target:
  entity_id: alarm_control_panel.home_alarm
data:
  code: "1234"
```
