### ISSUE TITLE
[Feature Request] Entity for 'Currently Open Zones' - for status and helps with Bypass on Honeywell / Ademco

### ISSUE THREAD

**Issue by Ltek** [ufodone/envisalink_new#195]
It would be nice to have a built-in (created and maintained by the Integration) a single entity that held a list of 'Currently Open Zones'

Looking for 2 features...

1. Basic list of Open Zones with time/date stamp -- this is great for mobile notifications and dashboard status views
2. An option to 'stop updating when panel in bypass' -- this helps track which zones are open when Honeywells/Ademco panels are in bypass since they show all bypassed zones as closed (but in reality they are open).

Below is code posted on the forum that shows how to script it but I think it would be far better in the Integration instead of separate...

```
alias: Bypass All Faulted Zones
sequence:
  - service: notify.notify
    data:
      message: "Generating zone string..."
  - variables:
      zone_numbers: []
      sensor_index: 0
  - repeat:
      until:
        condition: template
        value_template: "{{ sensor_index >= states.binary_sensor | selectattr('attributes.device', 'eq', 'envisalink') | selectattr('state', 'eq', 'on') | list | count }}"
      sequence:
        - variables:
            sensor: "{{ states.binary_sensor | selectattr('attributes.device', 'eq', 'envisalink') | selectattr('state', 'eq', 'on') | list | [sensor_index] | first }}"
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ sensor.attributes.zone is defined }}"
              sequence:
                - service: notify.notify
                  data:
                    message: "Adding zone {{ sensor.attributes.zone }} to the list."
                - service: variable.set
                  data:
                    variable: zone_numbers
                    value: "{{ zone_numbers + [sensor.attributes.zone | string] }}"
                - service: variable.set
                  data:
                    variable: sensor_index
                    value: "{{ sensor_index + 1 }}"
  - service: notify.notify
    data:
      message: "Generated zone numbers: {{ zone_numbers }}"
  - service: envisalink.alarm_keypress
    data:
      entity_id: alarm_control_panel.home_alarm
      keypress: {{ [states('sensor.alarm_user_code'), '6', zone_numbers_str] | join('')
        }}
```
