### ISSUE TITLE
Intermittent: All zones tripped when arming

### ISSUE THREAD

**Issue by ufodone** [ufodone/envisalink_new#26]
I’ve seen some weird behavior with the recent update, but I can’t seem to replicate. It appears (not sure) that during arming, all the zones are tripped. But the system is still able to be armed. So the Envisalink seems ok, it may be the integration logging the trips. When this happens and I disarm, all is cleared. I’ll keep monitoring.

_Originally posted by @larry-glz in https://github.com/ufodone/envisalink_new/issues/1#issuecomment-1442803743_

**Comment by ufodone** [comment]
@larry-glz I assume this is with the 0.6.2 release?  Do you have a Honeywell or DSC system?  

If you're able to capture the issue with debug logging turned on, that would be very helpful.  Thanks!

**Comment by larry-glz** [comment]
Yes, on the 0.6.2 with a Honeywell system.  Here's my config and the logs.  You'll see the system is initially Armed, then i disarm it.  When i arm it again, all the zones are triggered.

```
envisalink_new:
  host: 192.168.22.68
  panel_type: HONEYWELL
  user_name: !secret envisalink_username
  password: !secret envisalink_password
  code: !secret envisalink_code
  port: 4025
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 0 # was 30
  timeout: 15 # was 10
  panic_type: Police
  zones:
    1:
      name: "Main/Garage/Mud Rm Front Entries"
      type: "door"
    2:
      name: "Patio Entry"
      type: "door"
    3:
      name: "Lounge Entry"
      type: "door"
    4:
      name: "Kitchen/Laundry Windows"
      type: "window"
    5:
      name: "Master Bed/Bath Windows"
      type: "window"
    6:
      name: "Upstairs Openings"
      type: "opening"
    7:
      name: "Main Areas Motion"
      type: "motion"
    8:
      name: "Glass Break"
      type: "sound"
    9:
      name: "Alarm Garage Door 1"
      type: "garage_door"
    10:
      name: "Alarm Garage Door 2"
      type: "garage_door"
    11:
      name: "Mud Rm Motion"
      type: "motion"
    12:
      name: "Laundry Smoke"
      type: "smoke"
    13:
      name: "Family Rm Smoke"
      type: "smoke"
    14:
      name: "Upstairs Smoke"
      type: "smoke"
    15:
      name: "Security Rm Panic"
      type: "safety"
    16:
      name: "Mud Rm Rear Entry"
      type: "door"
  partitions:
    1:
      name: "Rancho Gonzalez Alarm"
```
[home-assistant_2023-02-24T15-33-18.488Z.log](https://github.com/ufodone/envisalink_new/files/10825940/home-assistant_2023-02-24T15-33-18.488Z.log)
