### ISSUE TITLE
Works great on my dsc panel  

### ISSUE THREAD

**Issue by progamer562** [ufodone/envisalink_new#31]
what i am is looking for pgm do they exist?

**Comment by progamer562** [comment]
and also strange bug when the system went out of fire alarm home assistant thinks the system is still an alarm the work around is turning the system on and off with the keypad

**Comment by ufodone** [comment]
>what i am is looking for pgm do they exist?

Are you referring to being able to trigger PGM 1 to 4 on the panel?  If so, you should be able to do that via the "invoke custom function" service call.  E.g.:

```
service: envisalink_new.invoke_custom_function
data:
  pgm: 2
target:
  entity_id: alarm_control_panel.home_alarm
```

> when the system went out of fire alarm home assistant thinks the system is still an alarm 

I'm not quite sure what this scenario is but if you're able to provide debug logging of it happening then I can take a look.

**Comment by progamer562** [comment]
sorry about that i saw that you need to call the service. for the pgm so thats fixed for me

and what type of logs your looking for

**Comment by ufodone** [comment]
Could you clarify what you mean by "fire alarm" and how are you triggering/clearing it?

For the logging, add something like the following to your configuration.yaml:

```
logger:
  default: info
  logs:
    custom_components.envisalink_new: debug
```

That will enable debug logging for the envisalink_new component.  If you can reproduce the issue and then attach the log file here I can take a look to see if I can figure out what's going on.
