### ISSUE TITLE
Discussion - testing Honeywell panel 

### ISSUE THREAD

**Issue by automation-dude-hass** [ufodone/envisalink_new#51]
Hi there,

I wanted to share some feedback with testing my Honeywell panel. This may be better as a discussion post but I cannot open one :) 

1. I migrated from a config-based setup. Changing from `envisalink` to `envislink_new` worked fine.
2. Using a Honeywell panel.
3. Zone updates are *really* fast now. This was my main gripe with the current version. I am using a dump interval of 3s but it seems much faster than that. 

Arming via HomeAssistant / HomeKit works now. My issue was on the Vista 20P side; evidently the EVL was on the same address as another keypad. Hazards of configuring without an alphanumeric keypad and doing it blind... ~I haven't been able to test arming as it only works in the EVL and not in HomeAssistant yet. I don't see any errors in the logs or anything, so I'm still debugging. It wasn't working beforehand so I'm 95% sure it's an issue on my end. If you have suggestions let me know. I did just try changing the password used for the TPI.~

**Comment by automation-dude-hass** [comment]
I was having issues with arming from Home Assistant working intermittently. Turns out, I had placed the EVL on the same address as another panel which was causing the problem. Arming from the UI works now. 

I did notice a few things: 

# Logbook spam when alarm triggered
I did notice that when the alarm goes off, the integration generates a *LOT* of messages like: 
<img width="336" alt="image" src="https://github.com/ufodone/envisalink_new/assets/118089781/8cd721c6-944a-42d9-8e25-7d25d3a22b54">.

It went on for a while, despite me canceling the alarm within 30 seconds. I am not sure why I see an `ALARM 04` message in the logbook for up to an hour.  The "Alarm Canceled" messages may be caused by me going into HomeKit and disabling the alarm from there (and it failing with retries due to the device address conflict). I'll try to find time to test this again. 


# Issue with hardware version detection 


The integration shows up as Hardware Version 3. I have an EVL4 MAX.
<img width="312" alt="image" src="https://github.com/ufodone/envisalink_new/assets/118089781/5fe7e66f-2922-441f-9146-41af86343d5c">

I have configured in the `configuration.yaml` to be `evil_version: 4`:
```yaml
envisalink_new:
    host: $HOST
    panel_type: HONEYWELL
    user_name: $PASSWORD # For Honeywell this must match password
    password: $PASSWORD
    evl_version: 4
    partitions:
        1: 
            name: "Home Alarm"
    zones:
        1:
            name: "Zone 1"
            type: "door"
... ...
```
