### ISSUE TITLE
Last Tripped Time Attribute Persist Through HA Restart

### ISSUE THREAD

**Issue by PablaV** [ufodone/envisalink_new#65]
Would it be possible to have the `last tripped time` attribute persist through a HA restart? It currently goes unknown after a restart. Also is it possible to have the format be similar to how HA uses the `last changed` attribute ie 2 hours ago instead of the date and time, maybe having two separate attributes cause I could see the exact date and time also being useful.

**Comment by bdf0506** [comment]
+1 for this.

I setup the original Envisalink integration back in 2018 and HA has changed a ton since then. IIRC, it resets not only after a restart, but also after the history/log recorder entry cycles. Here's the hack I've been doing via an automation to account for the fact that the last tripped time attribute doesn't persist. I manually created input_datetime sensors for each binary sensor and then did this, but I would love to see this handled natively in the integration. Even going this automation route, there may be a cleaner way to do this, as this was created in my HA instance in 2018 based on what was available in HA at the time.

````
alias: State change to input date
trigger:
  - platform: state
    entity_id:
      - binary_sensor.fire
      - binary_sensor.front_door
      - binary_sensor.garage_entry_door
      - binary_sensor.garage_door
      - binary_sensor.side_door
      - binary_sensor.basement_door
      - binary_sensor.left_gate
      - binary_sensor.right_gate
    from: "off"
    to: "on"
action:
  - service: input_datetime.set_datetime
    data:
      entity_id: |
        input_datetime.{{ trigger.entity_id|replace('binary_sensor.', '') }}
      timestamp: "{{ now().timestamp() }}"
mode: single
````
